### ISSUE TITLE
Why is dist committed?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/pelican-frontend#15]
Why not build the dist on deploy?

**Comment by jakubkrafka** [comment]
Can be removed, it's the old relict only. The new build system will rewrite that anyways. **But - requires redeployment of the old pelican, who still relies on that.**

**Comment by jpmckinney** [comment]
Well, the old Pelican does not have long to live, since I will be re-deploying it to an OCP server, and it should switch to the Docker deployment.

**Comment by jpmckinney** [comment]
Closed in b3dd806c0c8f66345958f0bd17c9bc3bea039ce0
