### ISSUE TITLE
Export report issue

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/pelican-frontend#22]
I'm trying to generate a report from https://dqt.datlab.eu/overview/311, but I have this problem:

![imagen](https://user-images.githubusercontent.com/48607824/132257919-d9f964bb-bdc9-461a-851f-961c668df7a8.png)

I gave the permissions to data-tools@open-contracting.org for the [report](https://docs.google.com/document/d/1yDmfdTyMxk_-JPEonV1alIxjPTBim0LSpYTwtD6roVE/edit?usp=sharing), the [folder](https://drive.google.com/drive/folders/1_04F9xGwV3mK9AhUEiB4vR9inRoORXKf), and the templates [1](https://docs.google.com/document/d/1A9oQb9_P_FhitoNQZnug0qR6D-P7QAGEd5kDSRFHUWY/edit) and [2](https://docs.google.com/document/d/1FZnOCMN1bJb9Sv8JEa7la3rouDHRdE0umWbibT2NIGY/edit#). I don't know what else could be, the pelican doesn't give me much information, maybe some misspelled command?

**Comment by aguilerapy** [comment]
This time I took the results and graphs from the pelican manually and replaced them with the report commands in order to finish it. Here is the copy of the report that has the commands: https://docs.google.com/document/d/1f_WzvjKBksg9XLjcEqk00VkIwYGBIBEjJ-cVNCsDFUI/edit?usp=sharing

**Comment by LucyAnne98** [comment]
> This time I took the results and graphs from the pelican manually and replaced them with the report commands in order to finish it. Here is the copy of the report that has the commands: https://docs.google.com/document/d/1f_WzvjKBksg9XLjcEqk00VkIwYGBIBEjJ-cVNCsDFUI/edit?usp=sharing

I am not able to open the file. Are permissions set correctly? 
@aguilerapy

**Comment by aguilerapy** [comment]
I opened the permissions for everyone https://docs.google.com/document/d/1f_WzvjKBksg9XLjcEqk00VkIwYGBIBEjJ-cVNCsDFUI/edit?usp=sharing

**Comment by jakubkrafka** [comment]
Fixed and deployed.

Assigning back to @aguilerapy, as I'm not sure about the OCP internal process with the issue lifecycle, @aguilerapy feel free to close the issue once reviewed, Thanks!

**Comment by jpmckinney** [comment]
Closing unless @aguilerapy has a comment.
