### ISSUE TITLE
Export: Don't fail if a check was not computed.

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/pelican-frontend#23]
The error message in https://github.com/open-contracting/pelican/issues/78 suggests that the export may fail if one of the checks referenced in it was not computed.

We need to prepare a report template that can be used for any dataset, so the export should not fail if a check was not computed. Otherwise, we would need to review the Pelican front-end and edit the report template before exporting a report.

**Comment by jakubkrafka** [comment]
The same situation as in #24
