### ISSUE TITLE
Export: The tag 'resultBoxImage' cannot be used in this context.

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/pelican-frontend#24]
**What were you trying to do?**

Generate a report with the following parameters:

Collection: uk_fts_2021-02-22 (Id 236)
Document id: 1FNpehBhSHNiXQ4Vm45AIMLeRPdkSv45t2aeccw-86j8
Folder id: 1OBPzTeoAOMqDtcxvQVribU2QTzAwP0e4
Report name: test output

**What error did you receive?**

![image](https://user-images.githubusercontent.com/19265814/120247563-08187380-c2c8-11eb-95dd-4ba3a9acc6ce.png)

link: https://docs.google.com/document/d/1lhHiK0RftAKooJ7whPgGbHt6HIOxTla7_JzQJhYmAIQ

**Did you attempt a fix?**

No, because the error message does not give enough information to understand which of the 18 references to the dataset check template in the main report template is causing the issue.

The first reference I added worked, so I assumed that resultBoxImage was a valid tag for all dataset checks.

**How soon do you need a fix?**

ASAP

**Related issues:**

https://github.com/open-contracting/pelican/issues/77

**Comment by jakubkrafka** [comment]
Deployed on https://dqt.datlab.eu.

The "error" was fixed in a quite complex matter. From now on, the "empty/non-calculated" checks in the report are not causing generation failures, instead:
1) comprehensive message is returned to the user with the list of checks, which weren't calculated (and thus generated)
2) there is red bold text in the template about missing values for check itself.

See screenshot ![Screenshot 2021-09-30 at 13 59 19](https://user-images.githubusercontent.com/2253943/135451312-72598b7c-1c7c-472b-98a9-6ca5b1b5a2aa.png)

**Comment by jpmckinney** [comment]
I'll mark as closed, but can re-open if any follow-up from users.

**Comment by duncandewhurst** [comment]
I tested the export with collection `indonesia_opentender_2021-09-01` (Id 349) and the other parameters the same as in the issue description and got the following error:

![image](https://user-images.githubusercontent.com/19265814/135783717-bf83ee3b-2305-486c-ac23-4a21993f26a0.png)

**Comment by jakubkrafka** [comment]
Beware - its not id 349 but indonesia_opentender_2021-09-01 (Id 348)
From logs:
```
Internal Server Error: /api/generate_report
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/src/app/dqt/views.py", line 300, in generate_report
    main_template, failed_tags = base.validate_and_process({})
  File "/usr/src/app/dqt/tools/tags/tag.py", line 435, in validate_and_process
    result, failed = tag.validate_and_process(new_data)
  File "/usr/src/app/dqt/tools/tags/tag.py", line 407, in validate_and_process
    new_data = self.prepare_data(data)
  File "/usr/src/app/dqt/tools/tags/template_tags/dataset.py", line 203, in prepare_data
    new_data["passedExamples"] = [example["ocid"] for example in check.meta["passed_examples"]]
  File "/usr/src/app/dqt/tools/tags/template_tags/dataset.py", line 203, in <listcomp>
    new_data["passedExamples"] = [example["ocid"] for example in check.meta["passed_examples"]]
KeyError: 'ocid'
```

**Comment by jpmckinney** [comment]
The different bug is fixed in https://github.com/open-contracting/pelican-frontend/pull/63
