### ISSUE TITLE
Document how to export dataset checks

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/pelican-frontend#25]
The [export template](https://docs.google.com/document/d/1L95LtX2O_3qfIHhNHRe-dmi4OJon_MiqMuZNXJj4CHk) only describes how to export field and resource checks.

Can we add some documentation on how to export dataset checks?

I discovered that there is a 'dataset' command. For example:

```
 {% dataset check:|distribution.tender_status| template:|1lhHiK0RftAKooJ7whPgGbHt6HIOxTla7_JzQJhYmAIQ| %}
```

But I'm unsure of what tags I can use in the template for dataset checks.

**Comment by jpmckinney** [comment]
Can also move a starred spreadsheet of commands to the docs.

Can review the folder(s) in Google Drive for content to include.
