### ISSUE TITLE
Add close and try again options to error message popup

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/pelican-frontend#27]
The error message should include actions for the user to take. The purpose fr the reload icon and button are unclear here, as it just runs the same inputs again, which will only take the user back to the same error message.

I suggest we include two clearly labelled buttons on the bottom right of the error message popup: 
1. Try again - this takes the user back to the Dataset report popup for the same collection for them to re-input the URL/IDs and report name.
2. Close - closes the window and returns the user to the Home screen

**Comment by jakubkrafka** [comment]
GUI was refactored - there are two buttons now. However 1. makes not a big sense - you typically want to fix the template and re-run the very same export again. Not to change template id and/or folder.
