### ISSUE TITLE
Add descriptions to checks

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/pelican-frontend#29]
From the [Tutorial Resource Template](https://docs.google.com/document/d/1nmSgUqYiISThHm5Ibs_gCbsM6HeMzEUfmuMAQJE0vCU/edit):

> For more detailed info on this check there is the {% description %} tag. The description tag is currently replaced by a Placeholder text. This is supposed to be replaced by a real description of a specific check.

Perhaps to begin with the {% description %} tag could just be replaced by the check description from the Pelican interface?

For example, for `consistent.period_duration_in_days`:

> For each period, `durationInDays` is equal to the difference between `startDate` and `endDate`. If `endDate` is blank or unparseable, then durationInDays is equal to the difference between `startDate` and `maxExtentDate`.
> 
> Since the test operates on all period objects, the test silently ignores any dates that can't be parsed.

We can then author more 'publisher friendly' descriptions as needed. I started a [spreadsheet](https://docs.google.com/spreadsheets/d/1WPPOSf7xM9LR3VlTGx7wyzc8q_5xQ3HyMoB8eaEWHDM/edit#gid=0) which we can use to record those.

**Comment by jpmckinney** [comment]
@duncandewhurst Is it fine to deploy with plain text (i.e. without the additional markup)?

**Comment by duncandewhurst** [comment]
> @duncandewhurst Is it fine to deploy with plain text (i.e. without the additional markup)?

Yes, that would be better than the status quo. Thanks!

**Comment by yolile** [comment]
> add a switch to report generation form (i.e. simple dropdown), indicating the language, which should be used

I think that should be enough, as we want the translations only to ease the report to the publishers, therefore, we don't need to translate the whole application.

**Comment by jpmckinney** [comment]
@duncandewhurst Is this feature still needed/desired? My understanding is that having analysts write and translate the descriptions directly in the templates is (1) just as much effort for analysts (they need to write the descriptions somewhere in all cases) and (2) much easier for analysts to edit (if provided by the app, then we need to do a whole rigamarole of changing the English translation, updating the Spanish translation, then re-deploying the service).

**Comment by duncandewhurst** [comment]
Yep, right now we only have one set of templates so this can be closed.
