### ISSUE TITLE
Remove passwords and token.pickle (x2)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/pelican-frontend#3]
We need to remove at least the passwords before making the repository public.

I can use https://rtyley.github.io/bfg-repo-cleaner/ to scrub passwords if needed (or we can just change them).

**Comment by jpmckinney** [comment]
I'll assume they are no longer used. Please change them if still in use.

**Comment by jakubkrafka** [comment]
I suggest doing this en bloc once everything will be in production (including Django etc.). Right now, rabbit, etc passwords/secrets will have to be shared with developers, testers - simply outside the OCP.
What should be changed:

- [ ] rabbit
- [ ] rabbit
- [ ] kingfisher-collect (rabbit, postgres)
- [ ] kingfisher-process (rabbit, postgres, django secret)
- [ ] data-registry (rabbit, postgres, django secret)
- [ ] pelican-frontend (rabbit, postgres, django secret, credentials token)
- [ ] pelican-backend (rabbit, postgres)

**Comment by jpmckinney** [comment]
Okay, this is all going in Salt, where Rabbit, PostgreSQL, and Django secrets have been redefined.

The credentials token has not been refreshed, though.
