### ISSUE TITLE
Is the term 'failed' appropriated for the 'Field is set' check?

### ISSUE THREAD

**Issue by yolile** [open-contracting/pelican-frontend#39]
For example:

![image](https://user-images.githubusercontent.com/6834122/73840120-3bdbaa00-47f6-11ea-9517-318d7a521106.png)

I understand that the 'Failed' term refers to the check it self, but if a term is not set ,that is not a failure, is just a coverage issue that says "the publisher doesnt publish this field" it doesnt imply that something is wrong. 

And actually the check was made and the result was that the field is not set, so I think that even for the check it self the term 'Failed' is not the most appropriated one.

**Comment by jpmckinney** [comment]
Noting that the component to edit is `CheckDetailResultBox`. We'll need to pass in the labels to use.
