### ISSUE TITLE
Tender Value Distribution chart in report generated from template

### ISSUE THREAD

**Issue by neelima-j** [open-contracting/pelican-frontend#85]
In the report generated from pelican using the [template](https://docs.google.com/document/d/1FNpehBhSHNiXQ4Vm45AIMLeRPdkSv45t2aeccw-86j8/edit#) the chart generated in the [Tender Values - Distribution](https://docs.google.com/document/d/1FNpehBhSHNiXQ4Vm45AIMLeRPdkSv45t2aeccw-86j8/edit#heading=h.2hxo79evpksl) section may be incorrect. 
Example: 
Tender value distribution [bar chart](https://dqt.datlab.eu/dataset/366/detail/distribution.tender_value) in pelican for Oyo State (Nigeria):
![Pelican chart](https://user-images.githubusercontent.com/78197684/148770536-80985057-5646-4fdb-ae0e-917ecdf6bddf.png)
Same chart in report generated as per [instructions](https://docs.google.com/document/d/1-eBvGqXQLLs_ORyZ8UteQ_8W-BCfpGFg1y3ThVFu4QU/):
![Generated report chart](https://user-images.githubusercontent.com/78197684/148770772-5aad019f-1338-411c-930b-9d00cbcdcd69.png)
The possible error could be:
- The report appears to calculate the bar lengths based on ratios of counts as opposed to values. 
- The first bar represents 2 contracting process that make 52% of the total value of all contracts. 
- Their count, 2, is 1% of the total number of processes (239)

**Comment by jpmckinney** [comment]
Thanks for reporting - the error with the chart in the report seems to be as you describe.
