### ISSUE TITLE
Coverage counts typos

### ISSUE THREAD

**Issue by yolile** [open-contracting/pelican-frontend#99]
https://github.com/open-contracting/pelican-frontend/blob/e5b63869ea5614376d8da22cba921336eec74f40/backend/controller/views.py#L137

Should be `tender.tenderers.id` instead? Should we have another one for `tender.numberOfTenderers`?

https://github.com/open-contracting/pelican-frontend/blob/e5b63869ea5614376d8da22cba921336eec74f40/backend/controller/views.py#L161

`contracts.amendments.id`

**Comment by jpmckinney** [comment]
Yes, those look like typos.

The meaning of the UI is "count of X objects", so `tenderers` is correct.
